### ISSUE TITLE
Example does not work, even after fixing the "Windows fix" :-)

### ISSUE THREAD

**Issue by R0binBl00d** [rm5248/m95-eeprom-arduino#1]
Hi,

what Arduino Version did you use for testing?
Just curious.

Best Regards

---
Arduino: 1.8.19 (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 921600, None, Disabled"

"C:\\Users\\x\\AppData\\Local\\Temp\\arduino_build_39230\\sketch\\m95_eeprom_m95256.ino.cpp.o"

m95_eeprom_m95256:12:19: error: invalid user-defined conversion from 'SPIClass*' to 'SPIClass&' [-fpermissive]

 M95_EEPROM eeprom(&SPI, EEPROM_CS, 64);

                   ^~~~

In file included from C:\Users\x\AppData\Local\Temp\arduino_modified_sketch_812801\m95_eeprom_m95256.ino:1:

C:\Users\x\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SPI\src/SPI.h:61:5: note: candidate is: 'SPIClass::SPIClass(uint8_t)' <near match>

     SPIClass(uint8_t spi_bus=HSPI);

     ^~~~~~~~

C:\Users\x\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SPI\src/SPI.h:61:5: note:   conversion of argument 1 would be ill-formed:

m95_eeprom_m95256:12:19: error: invalid conversion from 'SPIClass*' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]

 M95_EEPROM eeprom(&SPI, EEPROM_CS, 64);

                   ^~~~

m95_eeprom_m95256:12:19: error: invalid conversion from 'SPIClass*' to 'uint8_t' {aka 'unsigned char'} [-fpermissive]

In file included from C:\Users\x\AppData\Local\Temp\arduino_modified_sketch_812801\m95_eeprom_m95256.ino:1:

C:\Users\x\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SPI\src/SPI.h:61:22: note:   initializing argument 1 of 'SPIClass::SPIClass(uint8_t)'

     SPIClass(uint8_t spi_bus=HSPI);

m95_eeprom_m95256:12:38: error: conversion to non-const reference type 'class SPIClass&' from rvalue of type 'SPIClass' [-fpermissive]

 M95_EEPROM eeprom(&SPI, EEPROM_CS, 64);

                                      ^

In file included from C:\Users\x\AppData\Local\Temp\arduino_modified_sketch_812801\m95_eeprom_m95256.ino:3:

C:\Users\x\Documents\Arduino\libraries\M95_EEPROM\src/M95_EEPROM.h:12:3: note:   initializing argument 1 of 'M95_EEPROM::M95_EEPROM(SPIClass&, int, int)'

   M95_EEPROM(SPIClass& spi, int cs, int page_size);

   ^~~~~~~~~~

Using library SPI at version 2.0.0 in folder: C:\Users\x\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\SPI 

Using library M95_EEPROM at version 0.3.0 in folder: C:\Users\x\Documents\Arduino\libraries\M95_EEPROM 

exit status 1

invalid user-defined conversion from 'SPIClass*' to 'SPIClass&' [-fpermissive]

**Comment by rm5248** [comment]
whoops.  do `M95_EEPROM eeprom(SPI, EEPROM_CS, 64);` instead(remove the `&`).
